# Gitlab CI config for ArchLinux

dockerbuild:archlinux:
    image: docker:20.10.15
    services:
      - docker:20.10.15-dind
    stage: dockerbuild
    only:
        refs:
            - pushes
        changes:
            - hydrogenvr/ci/gitlab-ci/archlinux/install_dependencies.sh
            - hydrogenvr/ci/gitlab-ci/archlinux/Dockerfile
            - hydrogenvr/ci/gitlab-ci/archlinux/gitlab-ci.yml
            - '**/ci/gitlab-ci/archlinux/install_dependencies.sh'
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - if [[ -f ./project_directory.conf ]]; then . ./project_directory.conf ; else PROJECT_DIRECTORY=hydrogenvr/example ; fi
        - PROJ_INST_DEP=./$PROJECT_DIRECTORY/ci/gitlab-ci/archlinux/install_dependencies.sh
        - if [ ! -f $PROJ_INST_DEP ]; then PROJ_INST_DEP=./hydrogenvr/example/ci/gitlab-ci/archlinux/install_dependencies.sh; fi
        - docker build --pull --build-arg PROJECT_INSTALL_DEPS=$PROJ_INST_DEP -t $CI_REGISTRY_IMAGE:archlinux -f ./hydrogenvr/ci/gitlab-ci/archlinux/Dockerfile --no-cache --pull .
        - docker push $CI_REGISTRY_IMAGE:archlinux

build:archlinux:
    image: $CI_REGISTRY_IMAGE:archlinux
    stage: build
    only:
        - pushes
    script:
        - ./hydrogenvr/ci/gitlab-ci/archlinux/build.sh

