#version 420 core
#extension GL_ARB_compute_shader : enable

layout (local_size_x = LOCAL_SIZE_2D_X, local_size_y = LOCAL_SIZE_2D_Y) in;

// An image to store data into.
layout (rgba32f, binding = 0) writeonly uniform image2D dataOut;

void main()
{
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	vec2 globalSize = vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);

	imageStore(dataOut, pixel_coords, vec4(vec3(max(0, 1 - (pixel_coords.x % 5)) + max(0, 1 - (pixel_coords.y % 5))), 1.0));
	// imageStore(dataOut, pixel_coords, vec4(vec2(pixel_coords) / globalSize, 0.0, 1.0));
}
