branches:
  except:
    - /draft/
image:
- Visual Studio 2022
build:
    verbosity: detailed
environment:
  matrix:
    - BUILD_TYPE: 64bit
      INNOSETUPPATH: 'C:\Program Files (x86)\Inno Setup 6'
      PYTHON_PATH: 'C:\Python310-x64'
      PYTHON_URL: "https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip"

cache:
    - '%APPVEYOR_BUILD_FOLDER%\deps\KTX-Software -> **\install_scripts\libktx.sh'
    - '%APPVEYOR_BUILD_FOLDER%\deps\pythonqt -> **\install_scripts\pythonqt.sh'

install:
    - git submodule update --init --recursive
    - set Path=%INNOSETUPPATH%;%PATH%

    - cd %APPVEYOR_BUILD_FOLDER%
    - IF NOT EXIST project_directory.conf (set "PROJECT_DIRECTORY=example") ELSE (for /f "delims=" %%x in (project_directory.conf) do (set "%%x"))
    - IF NOT EXIST project_directory.conf (set "HVR_DIRECTORY=.")
    - set "PROJECT_DIRECTORY=%PROJECT_DIRECTORY:/=\%"
    - set "HVR_DIRECTORY=%HVR_DIRECTORY:/=\%"
    - echo %PROJECT_DIRECTORY%
    - set BUILD_CONF=%PROJECT_DIRECTORY%\build.conf
    - echo %BUILD_CONF%
    - for /f "delims=" %%x in (%BUILD_CONF%) do (set "%%x")

    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
    - ps: |
        $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
        $env:MSYSTEM = 'UCRT64'  # Start a 64 bit Mingw environment
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
    - C:\msys64\usr\bin\bash -lc "./%HVR_DIRECTORY%/ci/appveyor/install_dependencies.sh"

build_script:
    - C:\msys64\usr\bin\bash -lc "./%HVR_DIRECTORY%/ci/appveyor/build.sh"
    - set /p VERSION=<build\PROJECT_VERSION

after_build:
    - C:\msys64\usr\bin\bash -lc "./%HVR_DIRECTORY%/ci/appveyor/pack.sh"
    - set RELEASE_DIR_NAME=%PROJECT_NAME%-%VERSION%-windows-%BUILD_TYPE%
    - iscc.exe %ARCH% /DPROJECT_NAME=%PROJECT_NAME% /DPROJECT_MAINTAINER=%PROJECT_MAINTAINER% /DEXTERNAL_VERSION=%VERSION% /DPROJECT_URL=%PROJECT_URL% /DLICENSE=%APPVEYOR_BUILD_FOLDER%\LICENSE /DROOT_DIR=%APPVEYOR_BUILD_FOLDER%/%RELEASE_DIR_NAME% %APPVEYOR_BUILD_FOLDER%\%HVR_DIRECTORY%\innosetup\config.iss
    - move %APPVEYOR_BUILD_FOLDER%\%HVR_DIRECTORY%\innosetup\Output\setup.exe %APPVEYOR_BUILD_FOLDER%\%HVR_DIRECTORY%\innosetup\Output\%RELEASE_DIR_NAME%_setup.exe

artifacts:
  - path: '*.zip'
    name: zipfile
  - path: '**\innosetup\Output\*.exe'
    name: installer
