workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME != "draft"

stages:
    - dockerbuild
    - check
    - build
    - test
    - deploy

include:
    - hydrogenvr/ci/gitlab-ci/archlinux/gitlab-ci.yml
    - hydrogenvr/ci/gitlab-ci/ubuntu/22.04/gitlab-ci.yml
    - hydrogenvr/ci/gitlab-ci/ubuntu/24.04/gitlab-ci.yml
    - hydrogenvr/ci/gitlab-ci/appimage.yml
    - hydrogenvr/ci/gitlab-ci/maintainance.yml
