#version 430 core
#extension GL_ARB_compute_shader : enable

layout(local_size_x = LOCAL_SIZE_2D_X, local_size_y = LOCAL_SIZE_2D_Y) in;

// An image to store data into.
layout(rgba32f, binding = 0) readonly uniform image2D dataIn;
layout(rgba32f, binding = 1) writeonly uniform image2D dataOut;

uniform uint seed = 0;

#include <random.glsl>

void main()
{
	srand(seed * (gl_GlobalInvocationID.x + imageSize(dataIn).x * gl_GlobalInvocationID.y));
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	vec4 result        = imageLoad(dataIn, pixel_coords);
	imageStore(dataOut, pixel_coords, result * (randf4() * 0.4 + 0.6));
}
