PROJECT_NAME=VIRUP
PROJECT_ICON=icon.png
PROJECT_URL="https://gitlab.com/Dexter9313/virup"
PROJECT_DESCRIPTION="The VIrtual Reality Universe Project uses astrophysical data to propose a virtual reality visualization of it."
PROJECT_MAINTAINER="Florian Cabot <florian.cabot@epfl.ch>"
PROJECT_CHECK_FORMAT=true
PROJECT_CHECK_TIDY=true
PROJECT_CHECK_FORMAT_THIRDPARTY=true
PROJECT_CHECK_TIDY_THIRDPARTY=true
PROJECT_DOC=true
PROJECT_DOC_ENGINE=false
PROJECT_DOC_THIRDPARTY=true
PROJECT_TRANSLATE=true
PROJECT_TRANSLATE_ENGINE=false
PROJECT_TRANSLATE_THIRDPARTY=true
OPENGL_MAJOR_VERSION=4
OPENGL_MINOR_VERSION=2
OPENGL_PROFILE=Core
