get_filename_component(OCTREE_LIBRARY_NAME ${OCTREE_LIBRARY} NAME)
get_filename_component(OCTREE_LIBRARY_REALPATH ${OCTREE_LIBRARY} REALPATH)
INSTALL(FILES ${OCTREE_LIBRARY_REALPATH} DESTINATION lib RENAME ${OCTREE_LIBRARY_NAME})
